name: Deploy main branch

on:
  push:
    branches:
      - main
  #release:
  #  types: [published]
  #pull_request:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Install Plugin and Deploy
      id: install
      #if: github.event_name == 'pull_request'
      uses: serverless/github-action@v3.1
      with:
        #args: -c "serverless plugin install --name serverless-deployment-bucket && serverless remove --stage dev --region us-west-2 --verbose"
        args: -c "serverless plugin install --name serverless-deployment-bucket && serverless invoke local --function hello --stage $ENV_STAGE && sls deploy --stage $ENV_STAGE --region us-west-2 --verbose"
        entrypoint: /bin/sh
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        ENV_STAGE: prod
        # or if using AWS credentials directly
        #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
