name: deploy develop branch

on:
  push:
    branches:
      - develop


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [16.x]
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Install plugin and test
      uses: serverless/github-action@v3.1
      with:
        args: -c "sls plugin install --name serverless-deployment-bucket && sls invoke local --function hello --stage dev"
        entrypoint: /bin/sh
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    - name: deploy
      uses: serverless/github-action@v3.1
      with:
        args: -c "sls deploy --stage dev --region us-west-2 --verbose"
        entrypoint: /bin/sh
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}